### ISSUE TITLE
App crash for some users on production, possibly due to permission

### ISSUE THREAD

**Issue by raajnadar** [AllInOneYT/react-native-thermal-printer#44]
Error - 

```
com.dantsu.escposprinter.connection.bluetooth.BluetoothConnections.getList
java.lang.SecurityException
```

Stack trace - 

```
Exception java.lang.SecurityException:
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2426)
  at android.os.Parcel.createException (Parcel.java:2410)
  at android.os.Parcel.readException (Parcel.java:2393)
  at android.os.Parcel.readException (Parcel.java:2335)
  at android.bluetooth.IBluetooth$Stub$Proxy.getBondedDevices (IBluetooth.java:3264)
  at android.bluetooth.BluetoothAdapter.getBondedDevices (BluetoothAdapter.java:2497)
  at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnections.getList (BluetoothConnections.java)
  at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.getList (BluetoothPrintersConnections.java)
  at com.dantsu.escposprinter.connection.bluetooth.BluetoothPrintersConnections.selectFirstPaired (BluetoothPrintersConnections.java)
  at com.reactnativethermalprinter.ThermalPrinterModule.printBluetooth (ThermalPrinterModule.java)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java)
  at com.facebook.jni.NativeRunnable.run (NativeRunnable.java)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java)
  at java.lang.Thread.run (Thread.java:1012)
```

I have the required permissions on manifest

```
android.permission.BLUETOOTH, 
android.permission.BLUETOOTH_ADMIN, 
android.permission.BLUETOOTH_SCAN, 
android.permission.CAMERA, 
android.permission.INTERNET, 
```

Do we need runtime permission?

**Comment by raajnadar** [comment]
Now we are getting this error

Fatal Exception: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@b20d239c: AdapterService getBondedDevices
at com.android.bluetooth.Utils.checkPermissionForDataDelivery(Utils.java:490)
at com.android.bluetooth.Utils.checkConnectPermissionForDataDelivery(Utils.java:522)
at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getBondedDevices(AdapterService.java:2221)
at com.android.bluetooth.btservice.AdapterService$AdapterServiceBinder.getBondedDevices(AdapterService.java:2213)
at android.bluetooth.IBluetooth$Stub.onTransact(IBluetooth.java:642)
at android.os.Binder.execTransactInternal(Binder.java:1286)
at android.os.Binder.execTransact(Binder.java:1244)
